module.exports = {
  NODE_ENV: JSON.stringify('testing'),
  APP_HOST: JSON.stringify('https://test.medatc.cc'),
  APPV3: JSON.stringify('//v3.test.medatc.cc'),
  SIGNIN_URL: JSON.stringify('https://api.test.medatc.cc/user/sso/login'),
  FOUNDATION_API: JSON.stringify('https://api.test.medatc.cc/fdn/v1'),
  USER_API: JSON.stringify('https://api.test.medatc.cc/user'),
  ITEM_API: JSON.stringify('https://api.test.medatc.cc/item'),
  QUALITY_API: JSON.stringify('https://api.test.medatc.cc/quality'),
  FILE_API: JSON.stringify('https://api.test.medatc.cc/file'),
  CFG_API: JSON.stringify('https://api.test.medatc.cc/cfg'),
  MAINT_API: JSON.stringify('https://api.test.medatc.cc/maint/v2'),
  MAINT_API_V1: JSON.stringify('https://api.test.medatc.cc/maint'),
  PREP: JSON.stringify('https://test.medatc.cc/prep'),
  PREP_API: JSON.stringify('https://test.medatc.cc/prep/api'),
  PREP_URL: JSON.stringify('https://test.medatc.cc/prep/preparation'),
  WECHAT_URL: JSON.stringify('https://wechat.test.medatc.cc/#'),
  APPRAISE_URL: JSON.stringify('https://api.test.medatc.cc/comments'),
  OM_URL: JSON.stringify('https://api.test.medatc.cc/ops'),
  FBS_URL: JSON.stringify('https://api.test.medatc.cc/fbs')
}
